name: Deploy to AlwaysData

on:
  push:
    branches: [ main ]
    paths:
      - "BackEnd/**"
      - "server.js"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install rsync
        run: sudo apt-get update && sudo apt-get install -y rsync

      - name: Set up SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_alwaysdata
          chmod 600 ~/.ssh/id_alwaysdata
          echo "${{ secrets.SSH_KNOWN_HOSTS }}" > ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      - name: Deploy BackEnd folder
        run: |
          rsync -avz -e "ssh -i ~/.ssh/id_alwaysdata -o UserKnownHostsFile=~/.ssh/known_hosts" ./BackEnd/ rif@ssh-rif.alwaysdata.net:/home/rif/www/api-nandamotor/BackEnd/
